version: '3.9'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-container
    environment:
      - ORACLE_PASSWORD=oracle
      - ORACLE_DATABASE=employee_db
    ports:
      - "1521:1521" # Oracle database port

  employee-management-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee-management-app
    ports:
      - "8080:8080" # Spring Boot application port
    depends_on:
      - oracle-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/employee_db
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: oracle
